package main

import (
	"context"
	"fmt"
	"log"
	"net/http"

	"github.com/oashttp/oashttp"
)

type UpdateUserInput struct {
	ID   oashttp.UUID   `path:"id"`
	Body UpdateUserBody `body:"json"`
}

type UpdateUserBody struct {
	FullName    string  `json:"fullName" validate:"required,min=2,max=200"`
	Email       string  `json:"email" validate:"required,email"`
	PhoneNumber *string `json:"phoneNumber,omitempty" validate:"e164"`
}

type UserDTO struct {
	ID          oashttp.UUID `json:"id"`
	FullName    string       `json:"fullName"`
	Email       string       `json:"email"`
	PhoneNumber *string      `json:"phoneNumber,omitempty"`
}

type demoAuthenticator struct{}

func (demoAuthenticator) Authenticate(_ context.Context, token string) (*oashttp.Principal, error) {
	if token != "demo-token" {
		return nil, fmt.Errorf("invalid token")
	}
	return &oashttp.Principal{Subject: "demo-user", Features: map[string]struct{}{"core.users": {}}, Permissions: map[string]struct{}{"core.users.update": {}}}, nil
}

func newUsersApp(authenticator oashttp.Authenticator) *oashttp.App {
	app := oashttp.New(oashttp.Config{Info: oashttp.Info{Title: "Users API", Version: "1.0.0", Description: "Typed net/http API generated by oashttp."}, Authenticator: authenticator})
	core := app.Group("/api/v1").Group("/core")
	oashttp.MapPut(core, "/users/{id:uuid}", func(_ context.Context, input UpdateUserInput) oashttp.Result[UserDTO] {
		return oashttp.OK(UserDTO{ID: input.ID, FullName: input.Body.FullName, Email: input.Body.Email, PhoneNumber: input.Body.PhoneNumber})
	}).WithOperationID("updateUser").WithValidation().RequireFeatureAndPermission("core.users", "core.users.update").WithTags("Core / Users").WithSummary("Update user").WithDescription("Updates a user and returns Problem Details for errors.").Produces(http.StatusOK).ProducesProblem(http.StatusBadRequest).ProducesProblem(http.StatusUnauthorized).ProducesProblem(http.StatusForbidden).ProducesProblem(http.StatusNotFound)
	if err := app.MapOpenAPI("/openapi.json"); err != nil {
		panic(err)
	}
	if err := app.MapSwaggerUI("/swagger", oashttp.SwaggerUIConfig{DocumentURL: "/openapi.json"}); err != nil {
		panic(err)
	}
	return app
}

func main() {
	handler := newUsersApp(demoAuthenticator{}).MustBuild()
	log.Println("Users API listening on http://localhost:8080")
	log.Fatal(http.ListenAndServe(":8080", handler))
}
